config/routes.rb
Rails.application.routes.draw do
root 'notes#index'  

get 'hello/:message', to: 'notes#hello', as: :hello

get 'goodbye', to: 'notes#goodbye', as: :goodbye

get 'notes/new', to: 'notes#new', as: :new_note
get 'notes' , to: 'notes#index', as: :notes
post 'notes', to: 'notes#create'
get 'notes/:id/edit' , to: 'notes#edit', as: :edit_note
patch 'notes/:id' , to: 'notes#update' , as: :note

end

app/models/note.rb
class Note < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		puts "hello"
		puts params[:message]
		@message = params[:message]
		@notes=Note.all
		ap @notes
		
	end

	def hello
		puts "hello"
		puts params[:message]
		@message = params[:message]
	end

	def goodbye
		puts "goodbye"
		puts params[:message_goodbye]
		@message_goodbye = params[:message_goodbye]
		puts params
	end

	def new
		@note=Note.new
	end

	def edit
		puts params[:id]
		@note=Note.find(params[:id])
		ap @note
	end

    def update 
		
		note=Note.find(params[:id])
		note.user= params[:note][:user]
		note.content=params[:note][:content]
		note.save
		redirect_to notes_path
		
	end

	def create
		ap params
		note=Note.new
		note.user= params[:note][:user]
		note.content=params[:note][:content]
		note.save
		redirect_to notes_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNotes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>

<%=f.input :user %>
<%=f.input :content %>
<%=f.button :submit %>

<%end %>

app/views/notes/edit.html.erb
<h1> Edition de la note </h1>

<%= render 'form' %>


<link_to 'back', note_path 

app/views/notes/goodbye.html.erb
<% if @message_goodbye.present?%>
<h1> goodbye <%=@message_goodbye%></h1>
<%else%>
<h1> goodbye world</h1>
<%end%>

<%=form_tag("/goodbye", method:"get") do %>
<%=text_field_tag(:message_goodbye)%>
<%=submit_tag("send")%>
<%end%>


<%=link_to 'hello',hello_path(message: 'toto')%>



app/views/notes/hello.html.erb
<% if @message.present?%>
<h1> Hello <%=@message%> </h1>
<%else%>
<h1> Hello world 2</h1>
<%end%>
<%=link_to 'goodbye',goodbye_path()%>

app/views/notes/index.html.erb
<% if @message.present?%>
<h1> Hello <%=@message%>world </h1>
<%else%>
<h1> Hello world</h1>
<%end%>

<% @notes.each do |note| %>
	<div> <%=note.user%> </div>
	<div> <%=note.content%> </div>
	<%=link_to 'Editer la  note',edit_note_path(note.id)%>
<%end%>
<br>
<%=link_to 'Creer une nouvelle note',new_note_path()%>






app/views/notes/new.html.erb
<h1> Nouvelle note</h1>

<%= form_for(@note) do |f| %>

<div class="field">
	<%=f.label :user %>
	<%=f.text_field :user%>
</div>

<div class = "field">
    <%=f.label :content %>
	<%=f.text_field :content %>
</div>

<div class="actions">
	<%=f.submit %>
</div>

<%end %>